//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StadtfuehrungVeliLosinj {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StadtfuehrungVeliLosinj.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        internal static string AbbrechenButtonText {
            get {
                return ResourceManager.GetString("AbbrechenButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie müssen alle Felder ausfüllen! ähnelt.
        /// </summary>
        internal static string AlleFelderAusfüllen {
            get {
                return ResourceManager.GetString("AlleFelderAusfüllen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmelden ähnelt.
        /// </summary>
        internal static string AnmeldenButtonText {
            get {
                return ResourceManager.GetString("AnmeldenButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmeldung erfolgreich! ähnelt.
        /// </summary>
        internal static string AnmeldungErfolgreich {
            get {
                return ResourceManager.GetString("AnmeldungErfolgreich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzername oder Passwort ist falsch! ähnelt.
        /// </summary>
        internal static string AnmeldungFehlgeschlagen {
            get {
                return ResourceManager.GetString("AnmeldungFehlgeschlagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmeldung ähnelt.
        /// </summary>
        internal static string AnmeldungTitel {
            get {
                return ResourceManager.GetString("AnmeldungTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzername existiert nicht ähnelt.
        /// </summary>
        internal static string BenutzernameExistiertNicht {
            get {
                return ResourceManager.GetString("BenutzernameExistiertNicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzername ähnelt.
        /// </summary>
        internal static string BenutzernameLabel {
            get {
                return ResourceManager.GetString("BenutzernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzername ist vergeben! Geben Sie einen neuen Benutzername ein! ähnelt.
        /// </summary>
        internal static string BenutzernameVergeben {
            get {
                return ResourceManager.GetString("BenutzernameVergeben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abmelden ähnelt.
        /// </summary>
        internal static string buttonAbmeldenText {
            get {
                return ResourceManager.GetString("buttonAbmeldenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort zurücksetzen ähnelt.
        /// </summary>
        internal static string buttonPasswortZurueckSetzen {
            get {
                return ResourceManager.GetString("buttonPasswortZurueckSetzen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starte das Abenteuer ähnelt.
        /// </summary>
        internal static string buttonStartText {
            get {
                return ResourceManager.GetString("buttonStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Benutzerdatenbank ist derzeit leer! ähnelt.
        /// </summary>
        internal static string DatenbankIstLeer {
            get {
                return ResourceManager.GetString("DatenbankIstLeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-mail ähnelt.
        /// </summary>
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die E-mail Adresse muss ein gültiges Format haben ähnelt.
        /// </summary>
        internal static string EmailNachricht {
            get {
                return ResourceManager.GetString("EmailNachricht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Herzlichen Glückwunsch! Sie haben die Tour beendet! ähnelt.
        /// </summary>
        internal static string EndeDerTourNachricht {
            get {
                return ResourceManager.GetString("EndeDerTourNachricht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Öffnen des Anmeldeformulars ist ein Fehler aufgetreten ähnelt.
        /// </summary>
        internal static string FehlerAnmeldeFormOeffnen {
            get {
                return ResourceManager.GetString("FehlerAnmeldeFormOeffnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Hinzufügen eines Benutzers! ähnelt.
        /// </summary>
        internal static string FehlerBenutzerHinzufuegen {
            get {
                return ResourceManager.GetString("FehlerBenutzerHinzufuegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Öffnen des Registrierungsformulars ähnelt.
        /// </summary>
        internal static string FehlerRegistrierungsFormOeffnen {
            get {
                return ResourceManager.GetString("FehlerRegistrierungsFormOeffnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Ändern der Sprache ähnelt.
        /// </summary>
        internal static string FehlerSpracheAenderung {
            get {
                return ResourceManager.GetString("FehlerSpracheAenderung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Laden der Sprache ähnelt.
        /// </summary>
        internal static string FehlerSpracheLaden {
            get {
                return ResourceManager.GetString("FehlerSpracheLaden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die gewählte Sprache wird nicht unterstützt ähnelt.
        /// </summary>
        internal static string FehlerUngueltigeKultur {
            get {
                return ResourceManager.GetString("FehlerUngueltigeKultur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beginn der Reise ähnelt.
        /// </summary>
        internal static string labelBeginnText {
            get {
                return ResourceManager.GetString("labelBeginnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Punkte: ähnelt.
        /// </summary>
        internal static string LabelPunkteText {
            get {
                return ResourceManager.GetString("LabelPunkteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort bestätigen ähnelt.
        /// </summary>
        internal static string PasswortBestaetigen {
            get {
                return ResourceManager.GetString("PasswortBestaetigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dass Passwort muss mit dem oben eingegebenen übereinstimmen ähnelt.
        /// </summary>
        internal static string PasswortBestaetigenNachricht {
            get {
                return ResourceManager.GetString("PasswortBestaetigenNachricht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ähnelt.
        /// </summary>
        internal static string PasswortLabel {
            get {
                return ResourceManager.GetString("PasswortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Passwort muss mindestens 8 Zeichen, einen Buchstaben und ein Sonderzeichen enthalten ähnelt.
        /// </summary>
        internal static string PasswortNachricht {
            get {
                return ResourceManager.GetString("PasswortNachricht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort wurde zurückgesetzt ähnelt.
        /// </summary>
        internal static string PasswortZurueckGesetzt {
            get {
                return ResourceManager.GetString("PasswortZurueckGesetzt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rangliste ähnelt.
        /// </summary>
        internal static string RanglisteTitelText {
            get {
                return ResourceManager.GetString("RanglisteTitelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registrieren ähnelt.
        /// </summary>
        internal static string RegistrierenButtonText {
            get {
                return ResourceManager.GetString("RegistrierenButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registrierung erfolgreich! ähnelt.
        /// </summary>
        internal static string RegistrierungErfolgreich {
            get {
                return ResourceManager.GetString("RegistrierungErfolgreich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registrierung ähnelt.
        /// </summary>
        internal static string RegistrierungTitel {
            get {
                return ResourceManager.GetString("RegistrierungTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deutsch ähnelt.
        /// </summary>
        internal static string SpracheComboBox {
            get {
                return ResourceManager.GetString("SpracheComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache: ähnelt.
        /// </summary>
        internal static string SpracheLabelText {
            get {
                return ResourceManager.GetString("SpracheLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stadtführung Veli Lošinj ähnelt.
        /// </summary>
        internal static string StartSeiteTitel {
            get {
                return ResourceManager.GetString("StartSeiteTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein technischer Fehler ist aufgetreten  ähnelt.
        /// </summary>
        internal static string TechnischerFehler {
            get {
                return ResourceManager.GetString("TechnischerFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Herzlichen Glückwunsch, du hast die Tour durch Veli Lošinj erfolglreich abgeschlossen! ähnelt.
        /// </summary>
        internal static string TourAbschluss {
            get {
                return ResourceManager.GetString("TourAbschluss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen ähnelt.
        /// </summary>
        internal static string WillkommenText {
            get {
                return ResourceManager.GetString("WillkommenText", resourceCulture);
            }
        }
    }
}
