//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StadtfuehrungVeliLosinj {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RaetselText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RaetselText() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StadtfuehrungVeliLosinj.RaetselText", typeof(RaetselText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihre Antwort ist falsch! Versuchen Sie es noch einmal! ähnelt.
        /// </summary>
        internal static string FalscheAntwort {
            get {
                return ResourceManager.GetString("FalscheAntwort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hl. Johannes ähnelt.
        /// </summary>
        internal static string RätselFeral_AntwortA {
            get {
                return ResourceManager.GetString("RätselFeral_AntwortA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hl. Antonius ähnelt.
        /// </summary>
        internal static string RätselFeral_AntwortB {
            get {
                return ResourceManager.GetString("RätselFeral_AntwortB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hl. Nikolaus ähnelt.
        /// </summary>
        internal static string RätselFeral_AntwortC {
            get {
                return ResourceManager.GetString("RätselFeral_AntwortC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welchem Heiligen war die letzte Kirche geweiht? ähnelt.
        /// </summary>
        internal static string RätselFeral_Frage {
            get {
                return ResourceManager.GetString("RätselFeral_Frage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die B ähnelt.
        /// </summary>
        internal static string RätselFeral_RichtigeAntwort {
            get {
                return ResourceManager.GetString("RätselFeral_RichtigeAntwort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hl. Antonius ähnelt.
        /// </summary>
        internal static string RätselFischmarkt_AntwortA {
            get {
                return ResourceManager.GetString("RätselFischmarkt_AntwortA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hl. Nikolaus ähnelt.
        /// </summary>
        internal static string RätselFischmarkt_AntwortB {
            get {
                return ResourceManager.GetString("RätselFischmarkt_AntwortB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hl. Maria ähnelt.
        /// </summary>
        internal static string RätselFischmarkt_AntwortC {
            get {
                return ResourceManager.GetString("RätselFischmarkt_AntwortC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welchem Heiligen war die vorherige Kirche geweiht? ähnelt.
        /// </summary>
        internal static string RätselFischmarkt_Frage {
            get {
                return ResourceManager.GetString("RätselFischmarkt_Frage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C ähnelt.
        /// </summary>
        internal static string RätselFischmarkt_RichtigeAntwort {
            get {
                return ResourceManager.GetString("RätselFischmarkt_RichtigeAntwort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zum Verkauf von Öl ähnelt.
        /// </summary>
        internal static string RätselHafenVonRovenska_AntwortA {
            get {
                return ResourceManager.GetString("RätselHafenVonRovenska_AntwortA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Orientierung für Schiffe ähnelt.
        /// </summary>
        internal static string RätselHafenVonRovenska_AntwortB {
            get {
                return ResourceManager.GetString("RätselHafenVonRovenska_AntwortB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Glockenturm ähnelt.
        /// </summary>
        internal static string RätselHafenVonRovenska_AntwortC {
            get {
                return ResourceManager.GetString("RätselHafenVonRovenska_AntwortC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wozu dient der Feral? ähnelt.
        /// </summary>
        internal static string RätselHafenVonRovenska_Frage {
            get {
                return ResourceManager.GetString("RätselHafenVonRovenska_Frage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die B ähnelt.
        /// </summary>
        internal static string RätselHafenVonRovenska_RichtigeAntwort {
            get {
                return ResourceManager.GetString("RätselHafenVonRovenska_RichtigeAntwort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Turm ähnelt.
        /// </summary>
        internal static string RätselKircheHeiligeAntonius_AntwortA {
            get {
                return ResourceManager.GetString("RätselKircheHeiligeAntonius_AntwortA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leuchtturm ähnelt.
        /// </summary>
        internal static string RätselKircheHeiligeAntonius_AntwortB {
            get {
                return ResourceManager.GetString("RätselKircheHeiligeAntonius_AntwortB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Villa Elisabeth ähnelt.
        /// </summary>
        internal static string RätselKircheHeiligeAntonius_AntwortC {
            get {
                return ResourceManager.GetString("RätselKircheHeiligeAntonius_AntwortC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welches Gebäude diente als Verteidigungsfestung? ähnelt.
        /// </summary>
        internal static string RätselKircheHeiligeAntonius_Frage {
            get {
                return ResourceManager.GetString("RätselKircheHeiligeAntonius_Frage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A ähnelt.
        /// </summary>
        internal static string RätselKircheHeiligeAntonius_RichtigeAntwort {
            get {
                return ResourceManager.GetString("RätselKircheHeiligeAntonius_RichtigeAntwort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kaiser Franz Joseph ähnelt.
        /// </summary>
        internal static string RätselKircheHeiligeMaria_AntwortA {
            get {
                return ResourceManager.GetString("RätselKircheHeiligeMaria_AntwortA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine adelige Familie aus der 
        ///	Österreich-Ungarischen Monarchie ähnelt.
        /// </summary>
        internal static string RätselKircheHeiligeMaria_AntwortB {
            get {
                return ResourceManager.GetString("RätselKircheHeiligeMaria_AntwortB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seeleute ähnelt.
        /// </summary>
        internal static string RätselKircheHeiligeMaria_AntwortC {
            get {
                return ResourceManager.GetString("RätselKircheHeiligeMaria_AntwortC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wer wohnte in der Villa Elisabeth? ähnelt.
        /// </summary>
        internal static string RätselKircheHeiligeMaria_Frage {
            get {
                return ResourceManager.GetString("RätselKircheHeiligeMaria_Frage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die B ähnelt.
        /// </summary>
        internal static string RätselKircheHeiligeMaria_RichtigeAntwort {
            get {
                return ResourceManager.GetString("RätselKircheHeiligeMaria_RichtigeAntwort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Touristen ähnelt.
        /// </summary>
        internal static string RätselKircheHeiligeNikolaus_AntwortA {
            get {
                return ResourceManager.GetString("RätselKircheHeiligeNikolaus_AntwortA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erste Siedler ähnelt.
        /// </summary>
        internal static string RätselKircheHeiligeNikolaus_AntwortB {
            get {
                return ResourceManager.GetString("RätselKircheHeiligeNikolaus_AntwortB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mönche ähnelt.
        /// </summary>
        internal static string RätselKircheHeiligeNikolaus_AntwortC {
            get {
                return ResourceManager.GetString("RätselKircheHeiligeNikolaus_AntwortC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wer waren die ersten Siedler an der Stelle der heutigen Kirche des hl. Nikolaus? ähnelt.
        /// </summary>
        internal static string RätselKircheHeiligeNikolaus_Frage {
            get {
                return ResourceManager.GetString("RätselKircheHeiligeNikolaus_Frage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die B ähnelt.
        /// </summary>
        internal static string RätselKircheHeiligeNikolaus_RichtigeAntwort {
            get {
                return ResourceManager.GetString("RätselKircheHeiligeNikolaus_RichtigeAntwort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zagreb ähnelt.
        /// </summary>
        internal static string RätselOlivenmühle_AntwortA {
            get {
                return ResourceManager.GetString("RätselOlivenmühle_AntwortA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rovenska ähnelt.
        /// </summary>
        internal static string RätselOlivenmühle_AntwortB {
            get {
                return ResourceManager.GetString("RätselOlivenmühle_AntwortB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Osor ähnelt.
        /// </summary>
        internal static string RätselOlivenmühle_AntwortC {
            get {
                return ResourceManager.GetString("RätselOlivenmühle_AntwortC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welche Siedlung befindet sich in der Nähe des Hafens Rovenska? ähnelt.
        /// </summary>
        internal static string RätselOlivenmühle_Frage {
            get {
                return ResourceManager.GetString("RätselOlivenmühle_Frage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die B ähnelt.
        /// </summary>
        internal static string RätselOlivenmühle_RichtigeAntwort {
            get {
                return ResourceManager.GetString("RätselOlivenmühle_RichtigeAntwort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Olivenöl ähnelt.
        /// </summary>
        internal static string RätselTurm_AntwortA {
            get {
                return ResourceManager.GetString("RätselTurm_AntwortA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frischer Fisch ähnelt.
        /// </summary>
        internal static string RätselTurm_AntwortB {
            get {
                return ResourceManager.GetString("RätselTurm_AntwortB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Obst ähnelt.
        /// </summary>
        internal static string RätselTurm_AntwortC {
            get {
                return ResourceManager.GetString("RätselTurm_AntwortC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Was wurde früher in der Fischhalle verkauft? ähnelt.
        /// </summary>
        internal static string RätselTurm_Frage {
            get {
                return ResourceManager.GetString("RätselTurm_Frage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die B ähnelt.
        /// </summary>
        internal static string RätselTurm_RichtigeAntwort {
            get {
                return ResourceManager.GetString("RätselTurm_RichtigeAntwort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hl. Peter ähnelt.
        /// </summary>
        internal static string RätselVillaElisabeth_AntwortA {
            get {
                return ResourceManager.GetString("RätselVillaElisabeth_AntwortA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hl. Maria ähnelt.
        /// </summary>
        internal static string RätselVillaElisabeth_AntwortB {
            get {
                return ResourceManager.GetString("RätselVillaElisabeth_AntwortB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hl. Nikolaus ähnelt.
        /// </summary>
        internal static string RätselVillaElisabeth_AntwortC {
            get {
                return ResourceManager.GetString("RätselVillaElisabeth_AntwortC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wie heißt die Kirche, die du zuerst besucht hast? ähnelt.
        /// </summary>
        internal static string RätselVillaElisabeth_Frage {
            get {
                return ResourceManager.GetString("RätselVillaElisabeth_Frage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C ähnelt.
        /// </summary>
        internal static string RätselVillaElisabeth_RichtigeAntwort {
            get {
                return ResourceManager.GetString("RätselVillaElisabeth_RichtigeAntwort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fischhalle ähnelt.
        /// </summary>
        internal static string RätselWellenbrecher_AntwortA {
            get {
                return ResourceManager.GetString("RätselWellenbrecher_AntwortA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kirche der Hl. Maria ähnelt.
        /// </summary>
        internal static string RätselWellenbrecher_AntwortB {
            get {
                return ResourceManager.GetString("RätselWellenbrecher_AntwortB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ölmühle ähnelt.
        /// </summary>
        internal static string RätselWellenbrecher_AntwortC {
            get {
                return ResourceManager.GetString("RätselWellenbrecher_AntwortC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In welchem Gebäude wurden früher Oliven verarbeitet? ähnelt.
        /// </summary>
        internal static string RätselWellenbrecher_Frage {
            get {
                return ResourceManager.GetString("RätselWellenbrecher_Frage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C ähnelt.
        /// </summary>
        internal static string RätselWellenbrecher_RichtigeAntwort {
            get {
                return ResourceManager.GetString("RätselWellenbrecher_RichtigeAntwort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Ihre Antwort ist richtig! ähnelt.
        /// </summary>
        internal static string RichtigeAntwort {
            get {
                return ResourceManager.GetString("RichtigeAntwort", resourceCulture);
            }
        }
    }
}
