//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StadtfuehrungVeliLosinj {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sehenswuerdigkeiten {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sehenswuerdigkeiten() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StadtfuehrungVeliLosinj.Sehenswuerdigkeiten", typeof(Sehenswuerdigkeiten).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///			Willkommen in Veli Lošinj!
        ///
        ///			Willkommen zu einem lehrreichen Spiel durch das malerische Städtchen Veli Lošinj!
        ///
        ///			Entdecke interessante Fakten über seine Geschichte, Kultur und Natur.
        ///
        ///
        ///
        ///			Das Abenteuer beginnt bei der Kirche des hl. Nikolaus, wo sich die ersten Bewohner von Lošinj niedergelassen haben.
        ///
        ///			Bereit? Lass uns gemeinsam Veli Lošinj erkunden!
        ///		 ähnelt.
        /// </summary>
        internal static string Begrueßungsnachricht {
            get {
                return ResourceManager.GetString("Begrueßungsnachricht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schließen ähnelt.
        /// </summary>
        internal static string buttonSchließenText {
            get {
                return ResourceManager.GetString("buttonSchließenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///		Feral
        ///		
        ///	Der Teil von Veli Lošinj namens Feral war einst Standort einer meteorologischen Station, die von 1888 bis 1896 in Betrieb war. Auf der Promenade am Kap Leva war eine Wettersäule aufgestellt, von der heute nur noch der Sockel erhalten ist.
        ///
        ///	Besonderheit: Die hier durchgeführten Messungen erregten das Interesse Wiener Ärzte und trugen dazu bei, dass Veli und Mali Lošinj 1892 zu klimatischen Kurorten erklärt wurden.
        ///		 ähnelt.
        /// </summary>
        internal static string Feral {
            get {
                return ResourceManager.GetString("Feral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feral ähnelt.
        /// </summary>
        internal static string FeralTitel {
            get {
                return ResourceManager.GetString("FeralTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///		Fischmarkt
        ///		
        ///	Direkt am Meer gelegen, war der Fischmarkt schon immer das Zentrum des morgendlichen Treibens in Veli Lošinj. Einheimische und Touristen kamen hierher, um frischen Fisch direkt aus den Booten zu kaufen.
        ///
        ///	Besonderheit: Der Fischmarkt ist mehr als nur ein Verkaufsort – hier hört man die neuesten Geschichten, erfährt, wer was gefangen hat, und spürt den wahren Rhythmus des Insellebens.
        ///
        ///		 ähnelt.
        /// </summary>
        internal static string Fischmarkt {
            get {
                return ResourceManager.GetString("Fischmarkt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fischmarkt an der Uferpromenade ähnelt.
        /// </summary>
        internal static string FischmarktTitel {
            get {
                return ResourceManager.GetString("FischmarktTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///		Hafen von Rovenska
        ///		
        ///	Ein authentischer Fischerhafen mit traditionellen Booten und alten Steinhäusern, der seinen Charme und seine Atmosphäre vergangener Zeiten bewahrt hat.
        ///
        ///	Besonderheit: In Rovenska kann man noch heute Fischer beim Reparieren ihrer Netze beobachten – ein Ort gelebter Tradition.
        ///		 ähnelt.
        /// </summary>
        internal static string HafenVonRovenska {
            get {
                return ResourceManager.GetString("HafenVonRovenska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hafen von Rovenska ähnelt.
        /// </summary>
        internal static string HafenVonRovenskaTitel {
            get {
                return ResourceManager.GetString("HafenVonRovenskaTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///	    Kirche Heilige Antonius
        ///		
        ///	Eine imposante barock-klassizistische Kirche aus dem 18. Jahrhundert, direkt am Hafen gelegen. Sie wurde an der Stelle einer gotischen Kirche aus dem Jahr 1440 erbaut, die von einem Friedhof umgeben war und als erste selbstständige Pfarrkirche diente. Nach einem Brand im Jahr 1675 wurde die Kirche restauriert und erweitert, und ihr heutiges Aussehen erhielt sie 1774. 
        ///	Das Innere ist mit wertvollen Kunstwerken geschmückt, darunter ein Gemälde von Bartolomeo Vivarini aus [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string KircheHeiligeAntonius {
            get {
                return ResourceManager.GetString("KircheHeiligeAntonius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kirche des hl. Antonius ähnelt.
        /// </summary>
        internal static string KircheHeiligeAntoniusTitel {
            get {
                return ResourceManager.GetString("KircheHeiligeAntoniusTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///		Kirche Heilige Maria
        ///		
        ///	Eine der ältesten Kirchen in Veli Lošinj, äußerlich schlicht, aber im Inneren mit wertvollen Fresken aus dem Mittelalter geschmückt.
        ///
        ///	Besonderheit: Der Legende nach kamen die Dorfbewohner hierher, um in Zeiten großer Trockenheit um Regen zu beten.
        ///		 ähnelt.
        /// </summary>
        internal static string KircheHeiligeMaria {
            get {
                return ResourceManager.GetString("KircheHeiligeMaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kirche der hl. Maria ähnelt.
        /// </summary>
        internal static string KircheHeiligeMariaTitel {
            get {
                return ResourceManager.GetString("KircheHeiligeMariaTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///		Kirche Heilige Nikolaus
        ///		
        ///	Etwas außerhalb des Dorfzentrums gelegen, ist diese Kirche dem hl. Nikolaus – dem Schutzpatron der Seefahrer – gewidmet und war über Jahrhunderte ein spiritueller Zufluchtsort für Fischer und Kapitäne.
        ///
        ///	Besonderheit: Seeleute widmeten oft ihre Schiffskabinen dem hl. Nikolaus und baten um Schutz auf See.
        ///
        ///	Weitere Besonderheit: Vor der Kirche befindet sich eine Steinplatte mit den Namen der ersten 12 Familien, die sich in Veli Lošinj niedergelassen haben – die Gründervä [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string KircheHeiligeNikolaus {
            get {
                return ResourceManager.GetString("KircheHeiligeNikolaus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kirche des hl. Nikolaus ähnelt.
        /// </summary>
        internal static string KircheHeiligeNikolausTitel {
            get {
                return ResourceManager.GetString("KircheHeiligeNikolausTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///		Olivenmühle
        ///		
        ///	In der Bucht von Rovenska befindet sich eine alte Steinmühle, in der früher Oliven zu Öl verarbeitet wurden – eines der wichtigsten Produkte der Insel Lošinj. 
        ///	Die Mühle zeugt von der langen Tradition des Olivenanbaus und der Bedeutung des Olivenöls für die lokale Wirtschaft.
        ///
        ///	Besonderheit: Die Mühle wurde früher von Hand oder mit Hilfe von Tieren betrieben. Bewohner brachten ihre Oliven aus dem gesamten Inselgebiet hierher zur Verarbeitung.
        ///		 ähnelt.
        /// </summary>
        internal static string Olivenmühle {
            get {
                return ResourceManager.GetString("Olivenmühle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alte Olivenmühle  ähnelt.
        /// </summary>
        internal static string OlivenmühleTitel {
            get {
                return ResourceManager.GetString("OlivenmühleTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///		Turm
        ///		
        ///	Ein mittelalterlicher Verteidigungsturm aus dem 15. Jahrhundert, einst Teil des Schutzsystems gegen Piraten. Heute dient er als Museum und Galerie, mit einem herrlichen Ausblick von oben auf das Dorf und das Meer.
        ///
        ///	Besonderheit: Die alten Kanonen im Turm wurden nie im Kampf abgefeuert – Piraten flohen oft schon beim Anblick der Befestigung.
        ///		 ähnelt.
        /// </summary>
        internal static string Turm {
            get {
                return ResourceManager.GetString("Turm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Turm – Festung ähnelt.
        /// </summary>
        internal static string TurmTitel {
            get {
                return ResourceManager.GetString("TurmTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///		Villa Elisabeth
        ///		
        ///	Eine historische Villa aus der Zeit der österreichisch-ungarischen Monarchie, erbaut als Sommerresidenz einer wohlhabenden Familie. Ein architektonisches Juwel mit reicher Vergangenheit und heute ein bedeutendes Denkmal.
        ///
        ///	Besonderheit: Die Villa verfügte einst über einen privaten botanischen Garten und war eines der ersten Häuser auf der Insel mit modernem Badezimmer.
        ///		 ähnelt.
        /// </summary>
        internal static string VillaElisabeth {
            get {
                return ResourceManager.GetString("VillaElisabeth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Villa Elisabeth ähnelt.
        /// </summary>
        internal static string VillaElisabethTitel {
            get {
                return ResourceManager.GetString("VillaElisabethTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///		Wellenbrecher (Molo)
        ///		
        ///	Ein historischer Steindamm, der den Hafen schützt – ein beliebter Ort für Spaziergänge und Meerblick-Fotos.
        ///
        ///	Besonderheit: Alte Fischer warfen hier Münzen ins Meer, um vor der Abfahrt auf See Glück zu erbitten.
        ///		 ähnelt.
        /// </summary>
        internal static string Wellenbrecher_Molo_ {
            get {
                return ResourceManager.GetString("Wellenbrecher(Molo)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wellenbrecher (Molo) ähnelt.
        /// </summary>
        internal static string WellenbrecherTitel {
            get {
                return ResourceManager.GetString("WellenbrecherTitel", resourceCulture);
            }
        }
    }
}
